import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthProvider from "@/components/provider/AuthProvider";
import AppProvider from "@/components/provider/AppProvider";
import { ThemeProvider } from "next-themes";
import { Roboto } from "next/font/google";

// ✅ Google font optimization
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "Splurjj | Home",
    template: "%s | Splurjj",
  },
  description: "Generated by Splurjj description",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} antialiased`}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AuthProvider>
            <AppProvider>
              {children}
              <Toaster position="top-right" />
              <ToastContainer />
            </AppProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import "./globals.css";
// import { Toaster } from "@/components/ui/sonner";
// import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css";
// import AuthProvider from "@/components/provider/AuthProvider";
// import AppProvider from "@/components/provider/AppProvider";
// import { ThemeProvider } from "next-themes";
// import { Roboto } from "next/font/google";

// const roboto = Roboto({
//   subsets: ["latin"],
//   weight: ["400", "500", "700"],
//   variable: "--font-roboto",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "Splurjj | Home",
//   description: "Generated by splurjj description",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${roboto.className} antialiased`}
//       suppressHydrationWarning
//     >
//       <head>
//         <meta charSet="UTF-8" />
//       </head>
//       <body>
//         <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
//           <AuthProvider>
//             <AppProvider>
//               {children}
//               <Toaster position="top-right" />
//               <ToastContainer />
//             </AppProvider>
//           </AuthProvider>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }
